### ISSUE TITLE
Keep getting cookie agreement popup

### ISSUE THREAD

**Issue by bejli** [android-police/androidpolice-public#98] opened 2019-06-28 06:17 UTC
#### Expected behavior
I should only need to confirm my cookie settings once per device.

#### Actual behavior
I'm getting random cookie popups when checking articles.

#### Steps to reproduce the problem
Hard to reproduce, as situation happens randomly.

**Comment by archon810** [comment] 2021-04-21 19:49
We've now moved to using Google Funding Choices for the CMP, so hopefully the issue is no longer occurring for you. This is Google's own solution, and if something doesn't work, it's likely an issue on their side (or you've disabled something in your browser, like 3rd-party cookies). I'm going to close this.

**Closed by archon810** 2021-04-21 19:49 UTC
