### ISSUE TITLE
Swiping left on images is not possible!

### ISSUE THREAD

**Issue by HennyBro** [android-police/androidpolice-public#102] opened 2019-08-31 21:54 UTC
#### Expected behavior

Swiping left on images should show the next image that's in the image queue.

#### Actual behavior

Swiping left on images doesn't work at all. Only right swiping, which is illogical.

#### Steps to reproduce the problem

Try to swipe left on an image. 

#### Additional note

Maybe it's Android 10 Beta 6? Will check again after resetting Android 10 stable on September 3.
If the issue persists until then I'll update this thread! I hope you can find a fix quickly. :)

**Comment by archon810** [comment] 2019-08-31 22:20
Dupe of https://github.com/android-police/androidpolice-public/issues/100. The underlying issue and resolution are the same and are pending Google's fixes to core AMP.

**Closed by archon810** 2019-08-31 22:20 UTC
